using Hlibz.TypeRules.Analyzers.CodeFixes;

using static Hlibz.TypeRules.Analyzers.Tests.Verifier;

namespace Hlibz.TypeRules.Analyzers.Tests;

public sealed class SetterExceedsMaximumTests
{
    private const string PrivateSetters = """
        typerules.entities.match = T:App.Entity`1
        typerules.entities.max_setter_accessibility = private
        """;

    [Fact]
    public async Task Analyze_WithPublicSetter_ReportsTR301()
    {
        const string source = """
            namespace App;

            public sealed class Order : Entity<int>
            {
                public string Status { get; {|#0:set|}; } = "";
            }
            """;

        await VerifyAnalyzerAsync(
            PrivateSetters,
            source,
            Diagnostic(Descriptors.SetterExceedsMaximum)
                .WithLocation(0)
                .WithArguments("set", "Order.Status", "public", "'entities'", "private"));
    }

    [Fact]
    public async Task Analyze_WithPrivateSettersAndGetOnlyProperties_ReportsNothing()
    {
        const string source = """
            namespace App;

            public sealed class Order : Entity<int>
            {
                public string Status { get; private set; } = "";

                public int Total { get; }

                public int Count => 0;
            }
            """;

        await VerifyAnalyzerAsync(PrivateSetters, source);
    }

    [Fact]
    public async Task Analyze_WithPublicSetterOnInternalType_UsesEffectiveAccessibility()
    {
        const string configuration = """
            typerules.entities.match = T:App.Entity`1
            typerules.entities.max_setter_accessibility = internal
            """;
        const string source = """
            namespace App;

            internal sealed class Order : Entity<int>
            {
                public string Status { get; set; } = "";
            }
            """;

        await VerifyAnalyzerAsync(configuration, source);
    }

    [Fact]
    public async Task Analyze_WithInitAccessor_ReportsUnlessAllowed()
    {
        const string source = """
            namespace App;

            public sealed class Order : Entity<int>
            {
                public string Status { get; {|#0:init|}; } = "";
            }
            """;
        const string allowInit = PrivateSetters + "\ntyperules.entities.allow_init = true";

        await VerifyAnalyzerAsync(
            PrivateSetters,
            source,
            Diagnostic(Descriptors.SetterExceedsMaximum)
                .WithLocation(0)
                .WithArguments("init", "Order.Status", "public", "'entities'", "private"));
        await VerifyAnalyzerAsync(allowInit, source.Replace("{|#0:init|}", "init"));
    }

    [Fact]
    public async Task Analyze_WithOverrideAndExplicitImplementation_ReportsNothing()
    {
        const string source = """
            namespace App;

            public interface IHasStatus
            {
                string Status { get; set; }
            }

            public abstract class Document : Entity<int>
            {
                public abstract string Title { get; {|#1:set|}; }
            }

            public sealed class Invoice : Document, IHasStatus
            {
                public override string Title { get; set; } = "";

                string IHasStatus.Status { get; set; } = "";
            }
            """;

        await VerifyAnalyzerAsync(
            PrivateSetters,
            source,
            Diagnostic(Descriptors.SetterExceedsMaximum)
                .WithLocation(1)
                .WithArguments("set", "Document.Title", "public", "'entities'", "private"));
    }

    [Fact]
    public async Task Analyze_WithSetterInGeneratedPartialPart_ReportsNothing()
    {
        string[] sources =
        [
            """
            namespace App;

            public sealed partial class Order : Entity<int>
            {
                public string Status { get; private set; } = "";
            }
            """,
            """
            // <auto-generated/>
            namespace App;

            public sealed partial class Order
            {
                public string Generated { get; set; } = "";
            }
            """,
        ];

        await VerifyAnalyzerAsync(PrivateSetters, sources);
    }

    [Fact]
    public async Task Fix_WithPublicSetter_MakesItPrivate()
    {
        const string source = """
            namespace App;

            public sealed class Order : Entity<int>
            {
                public string Status { get; {|#0:set|}; } = "";

                public int Total
                {
                    get;
                    internal {|#1:set|};
                }
            }
            """;
        const string fixedSource = """
            namespace App;

            public sealed class Order : Entity<int>
            {
                public string Status { get; private set; } = "";

                public int Total
                {
                    get;
                    private set;
                }
            }
            """;

        await VerifyCodeFixAsync<RestrictSetterCodeFixProvider>(
            PrivateSetters,
            source,
            fixedSource,
            Diagnostic(Descriptors.SetterExceedsMaximum)
                .WithLocation(0)
                .WithArguments("set", "Order.Status", "public", "'entities'", "private"),
            Diagnostic(Descriptors.SetterExceedsMaximum)
                .WithLocation(1)
                .WithArguments("set", "Order.Total", "internal", "'entities'", "private"));
    }

    [Fact]
    public async Task Fix_WithProtectedMaximumInUnsealedClass_MakesItProtected()
    {
        const string configuration = """
            typerules.entities.match = T:App.Entity`1
            typerules.entities.max_setter_accessibility = protected
            """;
        const string source = """
            namespace App;

            public class Order : Entity<int>
            {
                public string Status { get; {|#0:set|}; } = "";
            }
            """;
        const string fixedSource = """
            namespace App;

            public class Order : Entity<int>
            {
                public string Status { get; protected set; } = "";
            }
            """;

        await VerifyCodeFixAsync<RestrictSetterCodeFixProvider>(
            configuration,
            source,
            fixedSource,
            Diagnostic(Descriptors.SetterExceedsMaximum)
                .WithLocation(0)
                .WithArguments("set", "Order.Status", "public", "'entities'", "protected"));
    }

    [Fact]
    public async Task Fix_WithRequiredOrInterfaceOrVirtualProperty_OffersNoFix()
    {
        const string source = """
            namespace App;

            public interface IHasStatus
            {
                string Status { get; set; }
            }

            public class Order : Entity<int>, IHasStatus
            {
                public required string Number { get; {|#0:set|}; }

                public string Status { get; {|#1:set|}; } = "";

                public virtual string Note { get; {|#2:set|}; } = "";
            }
            """;

        await VerifyCodeFixAsync<RestrictSetterCodeFixProvider>(
            PrivateSetters,
            source,
            source,
            Diagnostic(Descriptors.SetterExceedsMaximum)
                .WithLocation(0)
                .WithArguments("set", "Order.Number", "public", "'entities'", "private"),
            Diagnostic(Descriptors.SetterExceedsMaximum)
                .WithLocation(1)
                .WithArguments("set", "Order.Status", "public", "'entities'", "private"),
            Diagnostic(Descriptors.SetterExceedsMaximum)
                .WithLocation(2)
                .WithArguments("set", "Order.Note", "public", "'entities'", "private"));
    }

    [Fact]
    public async Task Fix_WithPositionalRecordProperty_OffersNoFix()
    {
        const string configuration = """
            typerules.endpoints.match = T:App.IEndpoint
            typerules.endpoints.max_setter_accessibility = private
            """;
        const string source = """
            namespace App;

            public sealed record Ping(string {|#0:Status|}) : IEndpoint;
            """;

        await VerifyCodeFixAsync<RestrictSetterCodeFixProvider>(
            configuration,
            source,
            source,
            Diagnostic(Descriptors.SetterExceedsMaximum)
                .WithLocation(0)
                .WithArguments("init", "Ping.Status", "public", "'endpoints'", "private"));
    }

    [Fact]
    public async Task Parse_WithAllowInitAlone_ReportsTR000()
    {
        const string configuration = """
            typerules.entities.match = T:App.Entity`1
            typerules.entities.require_sealed = true
            typerules.entities.allow_init = true
            """;
        const string source = """
            namespace App;

            internal sealed class Order : Entity<int> { }
            """;

        await VerifyAnalyzerAsync(
            configuration,
            source,
            Diagnostic(Descriptors.InvalidConfiguration).WithArguments(
                "rule set 'entities' sets allow_init without max_setter_accessibility, which it "
                + "modifies"));
    }
}
